version: 2.1

parameters:
  service_name:
    type: boolean
    default: false

jobs:
  service1-deploy-dev:
    docker:
      - image: << pipeline.parameters.node-image >>
    steps:
      - attach_workspace:
          at: ~/project
      - nx/set-shas
      - run:
          name: Deploy Dev
          command: echo Service 1 deployed to dev
  service1-deploy-prod:
    docker:
      - image: << pipeline.parameters.node-image >>
    steps:
      - attach_workspace:
          at: ~/project
      - nx/set-shas
      - run:
          name: Deploy Prod
          command: echo Service 1 deployed to prod

workflows:
  service1:
    when: << pipeline.parameters.service_name >>
    jobs:
      - common-install-dependencies
      - service1-deploy-dev:
          requires:
            - common-install-dependencies
          filters:
            branches:
              only: main
      - request-approval:
          type: approval
          requires:
            - deploy-dev
          filters:
            branches:
              only: main
      - service1-deploy-prod:
          requires:
            - request-approval
          filters:
            branches:
              only: main
